services:
  nestjs-blue:
    image: ${NESTJS_BLUE_IMAGE}:${TAG_BLUE}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - main-protostar
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: '512M' 
          cpus: '1.0'
        reservations:
          memory: '256M'
          cpus: '0.5'

  nestjs-green:
    image: ${NESTJS_GREEN_IMAGE}:${TAG_GREEN}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - main-protostar
    env_file: .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: '512M' 
          cpus: '1.0'
        reservations:
          memory: '256M'
          cpus: '0.5'

networks:
  main-protostar:
    external: true
    name: main-protostar