services:
  nestjs-blue:
    container_name: main-nestjs-blue
    image: ${NESTJS_BLUE_IMAGE}:${TAG_BLUE}
    networks:
      - main-protostar
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}  # 호스트 환경 변수 주입
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: '512M' 
        reservations:
          memory: '256M'

  nestjs-green:
    container_name: main-nestjs-green
    image: ${NESTJS_GREEN_IMAGE}:${TAG_GREEN}
    networks:
      - main-protostar
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}  # 호스트 환경 변수 주입
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: '512M' 
        reservations:
          memory: '256M'

networks:
  main-protostar:
    external: true
    name: main-protostar