# Docker Compose 파일 형식 버전
name: project-protostar-backend
services:
  nestjs-dev:
    container_name: protostar-nest-dev
    build:
      context: .
      target: dev_runner
    command: sh -c "pnpm start:watch"
    ports:
      - '5859:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: '512M' 
        reservations:
          memory: '256M'
    networks:
      - main-protostar
    
  nestjs-prod:
    container_name: protostar-nest-prod
    build:
      context: .
    ports:
      - '5859:3000'
    environment:
      - NODE_ENV=production
    # env_file: # local 돌리시 켜줘야 함!!!
    #   - .env
    deploy:
      resources:
        limits:
          memory: '512M' 
        reservations:
          memory: '256M'
    networks:
      - main-protostar

networks:
  main-protostar:
    external: true
    name: main-protostar